use DLithe;


--=====================================================
CREATE TABLE CONSTRAINT_DEMO
(
ID INT,
NAME VARCHAR(25) NOT NULL,
AGE INT CHECK(AGE>18),             --COLOUMN LEVEL
ADDRESS VARCHAR(25) DEFAULT 'BANGALORE',
CONSTRAINT PK_ID PRIMARY KEY(ID)
);


--===========================================

CREATE TABLE CONSTRAINT_DEMO2
(
ID INT,
NAME VARCHAR(25) NOT NULL,
AGE INT,
ADDRESS VARCHAR(25) DEFAULT 'BANGALORE',
CONSTRAINT PK_ID2 PRIMARY KEY(ID),   --TABLE LEVEL
CONSTRAINT CK_AGE CHECK(AGE>18)
);